# site settings
email: rippleytrigger@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Márques
jekyll_integrator_name: Andrew Banchich
jekyll_integrator_url: http://andrewbanchi.ch
street_address: 
city: Barcelona
state: Ca
zip_code: 08019
country: Spain
phone: (+34) 692-661337

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/rippleytrigger
  GitLab: https://gitlab.com/rippleytrigger
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/rippleytrigger/
  Twitter: https://twitter.com/Rippleytrigger
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 

# To Allow Post Categories
permalink: /:categories/:title

default_lang: es

defaults:
  - scope:
      path: ""
    values:
      lang: "es"

  - scope:
      path: "en"
    values:
      lang: "en"

  - scope:
      path: "ca"
    values:
      lang: "ca"
